name: id
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: id
        run: >-
          echo "uid=$(id -u ${USER})" >> "$GITHUB_OUTPUT" &&
          echo "gid=$(id -g ${USER})" >> "$GITHUB_OUTPUT"
      - run: echo ${{steps.id.outputs.uid}}
      - run: echo ${{steps.id.outputs.gid}}
      # - name: Build
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: hugomods/hugo:exts-0.123.7
      #     options: >-
      #       -v ${{ github.workspace }}:/src
      #       -v /tmp/hugo_cache:/tmp/hugo_cache
      #       -u $(id -u ${USER}):$(id -g ${USER})
      #       -e GITHUB_TOKEN
      #     run: hugo version
